In [1]:
=============Pandas======================
1) pandas     :   Data frame or data applications
2) numpy      :   Numerical python or math operations
3) matplotlib :   For plots graphs
4) Seaborn    :   For plots graphs
5) Bokhe      :   For plots
6) plotly     :   For plots

============== Machine learning =========
7) Scikit learn(Sklearn) : ML models
8) stat                  : statistical models
===========Data retrieval from sql scrapping ===============
9) sqlite                : Connect with database
10)Beautiful soup        : scrap the data from website
11) Websocket            : scrap

============Deep Learning==================
12) Tensorflow          : Google
13) Keras               : DL Models
14) OpenCV              : Image Operations
15)Pillow(PIL)          : Image Operations
16) Pytorch             : Facebook
17) Pretrained model
    VGG16
    Mobilenet
    RESNET
    RCNN
    MASKRCNN
    FASTERCNN
    YOLO
==============Natural Language Processing =================
18) NLTK         :   Natural Language Process
19) Scipy        :   
20) Word2vec(How words will convert to vector representation) :
21) GolVE        :
22) Wordcloud    :


=====================Hugging face ======================
23) Transformers :   BERT Models  (Bidirectional Encoder Representations from Transformers)

=======================Gen AI Models ==================
24) Open AI + Microsfot  : GPT(Generative pre-trained transformer)
25) Google               : Gemini AI
26) Amazon               : Q
27) Meta                 : Meta AI
28) Apple                :

LLAMMA, 
GEMMA, 
Dalle-E, 
T5

All are having different packages

======================LANGCHAIN ====================
29) Langchain framework

======================Deployemnts ======================
30) Flask
31) Streamlt
32) Django
====================MLops===========================
34) Mlflow
35) Kubeflow
36) Azure Ai services : Azure packages
37) GCP               : GCP Packages



SyntaxError: unmatched ')' (3493735362.py, line 2)

In [ ]:
**Step-1**
** Create a data frame**
   --We will create a data frame using list
   --We will create a data frame using dictionary
    

In [ ]:
import pandas as pd

In [8]:
d1 = pd.DataFrame()
type(d1)

NameError: name 'pd' is not defined

In [7]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [3]:
d1=pd.DataFrame()
type(d1)

pandas.core.frame.DataFrame

In [ ]:
***** step-2 Provide the data*****

In [10]:
name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
place = ['Hyd', 'Blr', 'Chn']
data = zip(name, age, place)
pd.DataFrame(data, columns=['Name', 'Age', 'Place'])

Name  Age Place
0    Tarun   20   Hyd
1   Venkat   35   Blr
2  Sahasra   12   Chn

In [ ]:
***** Step-4 : Providing Index ************

In [13]:
####

name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
place = ['Hyd', 'Blr', 'Chn']
data = zip(name, age, place)
ix = ['A', 'B', 'C']
column=['Name', 'Age', 'Place']
pd.DataFrame(data, index=ix, columns=column)

Name  Age Place
A    Tarun   20   Hyd
B   Venkat   35   Blr
C  Sahasra   12   Chn

In [14]:
name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
city = ['Hyd', 'Blr', 'Chn']
data = zip(name, age)
column=['Name', 'Age']
pd.DataFrame(data, index=city, columns=column)

Name  Age
Hyd    Tarun   20
Blr   Venkat   35
Chn  Sahasra   12

In [27]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
print(df)
print(df.loc[0])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64


In [31]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
index1 = ['A', 'B', 'C']
df = pd.DataFrame(data, index=index1)
print(df)
print(df.loc("A"))

   calories  duration
A       420        50
B       380        40
C       390        45


ValueError: No axis named A for object type DataFrame

In [ ]:
-Create a data frame
-Provide the data
-Add the columns
-Provide the index

In [32]:
import pandas as pd
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
- Add a new column on existing data frame
   - If we want to add new column, require to check how many columns we have there(Ex: 3).
    - Our new columns also should have same number of clumns(Ex:3)
    - Suppose, I want to create new column, called salary.
     - Make a list 3 values.
      - salary=[1000,2000,3000]
*** Synatx****
     dataframe[salary] = list of values

In [42]:
import pandas as pd

data = {
    "name" : ['venkat', 'balaji', 'shiva'],
    "age" : [25, 22, 32],
    "city" : ['Hyd', 'Blr', 'Chn']
}
d1 = pd.DataFrame(data)
salary=[1000,2000,3000]
d1['salary'] = salary
print(d1)

     name  age city  salary
0  venkat   25  Hyd    1000
1  balaji   22  Blr    2000
2   shiva   32  Chn    3000


In [51]:
#Create empty data frame list
# Create 3 lists using list comphrensio 
#list1 = values from 1 to 10
#list2 = square of 1 to 10
#list3 = cube of 1 to 10
# Finally make a data frame.

import pandas as pd
d1 = pd.DataFrame()
list1 = [i for i in range(1, 11)]
list2 = [i**2 for i in range(1, 11)]
list3 = [i**3 for i in range(1, 11)]
data = zip(list1, list2, list3)
d1['X'] = list1
d1['Y'] = list2
d1['Z'] = list3
print(d1)

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000


In [ ]:
**Step-6
Update the values for existing column

In [ ]:
- Create a new column, update the exiting column are same way only.
- Here also we need to make a list of values=number of rows

In [56]:
import pandas as pd
name = ['venkat', 'balaji', 'Priya']
age = [22, 24, 16]
salary = [1000, 2000, 3000]
city = ['Hyd', 'Blr', 'Chn']
column = ['Name', 'City', 'Age', 'Salary']
data = zip(name, city, age, salary)
d1 = pd.DataFrame(data, columns=column)
print(d1)
salary2 = [5000, 10000, 15000]
d1['Salary'] = salary2
print('\n',d1)
d1['Date Of Birth'] = ['16-July-2000', '12-Dec-2012', '19-Feb-2010']
d1['Gender'] = ['M', 'M', 'F']
d1['Gender'] = ['M', 'M', 'F']
print('\n',d1)

     Name City  Age  Salary
0  venkat  Hyd   22    1000
1  balaji  Blr   24    2000
2   Priya  Chn   16    3000

      Name City  Age  Salary
0  venkat  Hyd   22    5000
1  balaji  Blr   24   10000
2   Priya  Chn   16   15000

      Name City  Age  Salary Date Of Birth Gender
0  venkat  Hyd   22    5000  16-July-2000      M
1  balaji  Blr   24   10000   12-Dec-2012      M
2   Priya  Chn   16   15000   19-Feb-2010      F


In [ ]:
** Step-7: How to drop the column
 - How to check the columns?
 ---- If we want to drop a specific column, we will use drop method.
----- We already know differnce between keywords and methods
---   Keywords will use directly 
---- Methods will use corresponding data frame.
---- Method name : drop
---- Axis:  Represents the specified vlaue is a row or column
      -- axis = 0 --> Row   (This is by default)
      -- axis = 1 --> Column
---- inplace : Override the data frame or not.
         inplace = True --> Override the frame
         inplace = False --> The modified data frame will be use when you provide new variable for the operation

In [66]:
import pandas as pd
name = ['venkat', 'balaji', 'Priya']
age = [22, 24, 16]
salary = [1000, 2000, 3000]
city = ['Hyd', 'Blr', 'Chn']
column = ['Name', 'City', 'Age', 'Salary']
data = zip(name, city, age, salary)
d2 = pd.DataFrame(data, columns=column)
#print(d2)
salary2 = [5000, 10000, 15000]
d2['Salary'] = salary2
#print('\n',d2)
d2['Date Of Birth'] = ['16-July-2000', '12-Dec-2012', '19-Feb-2010']
d2['Gender'] = ['M', 'M', 'F']
d2['Gender'] = ['M', 'M', 'F']
d2['designation'] = ['Manager', 'Engineer', 'Director']
#print('\n',d2)
d2.drop('Gender', axis=1, inplace=True)
print('\n',d2)


      Name City  Age  Salary Date Of Birth designation
0  venkat  Hyd   22    5000  16-July-2000     Manager
1  balaji  Blr   24   10000   12-Dec-2012    Engineer
2   Priya  Chn   16   15000   19-Feb-2010    Director


In [67]:
import pandas as pd
name = ['venkat', 'balaji', 'Priya']
age = [22, 24, 16]
salary = [1000, 2000, 3000]
data = zip(name, age, salary)
d1 = pd.DataFrame(data)
print(d1)

        0   1     2
0  venkat  22  1000
1  balaji  24  2000
2   Priya  16  3000


In [ ]:
Step - 8 --- Drop the row

- Drop the row and drop the column both are same only
   -- The only difference is axis
     axis = 0 represents rows
     axis = 1 represents column
      - By default axis = 0 available
       which means if we provide any value, it will represent rows only.


           

In [71]:
import pandas as pd
df2 = pd.DataFrame()
l1 = [i for i in range(1, 11)]
l2 = [i ** 2 for i in range(1, 11)]
l3 = [i ** 3 for i in range(1, 11)]

df2['Number1'] = l1
df2['Number2'] = l2
df2['Number3'] = l3
print(df2)
df2.drop(4)

   Number1  Number2  Number3
0        1        1        1
1        2        4        8
2        3        9       27
3        4       16       64
4        5       25      125
5        6       36      216
6        7       49      343
7        8       64      512
8        9       81      729
9       10      100     1000


Number1  Number2  Number3
0        1        1        1
1        2        4        8
2        3        9       27
3        4       16       64
5        6       36      216
6        7       49      343
7        8       64      512
8        9       81      729
9       10      100     1000

In [72]:
#To drop Multiple rows or Multiple columns by using the list.

df2.drop([4,8])

Number1  Number2  Number3
0        1        1        1
1        2        4        8
2        3        9       27
3        4       16       64
5        6       36      216
6        7       49      343
7        8       64      512
9       10      100     1000

In [ ]:
We will use the index for both rows and columns, but the index wil be used based on axis.
if axis=0 ---> Rows(It is by default if we did not specify it)
if axis=1 ---> Columns.

In [73]:
df2.drop([0,1], axis=1)

KeyError: '[0, 1] not found in axis'

In [ ]:
Step-9:  How to select the column?

In [77]:
# Series type
df2['Number1']
type(df2['Number1'])

#Series type:
    # No column display
    #Whenever you see this type: Series type


pandas.core.series.Series

In [78]:
df2[['Number2']]
type(df2[['Number2']])
# Data frame

pandas.core.frame.DataFrame

In [80]:
df2.Number2
type(df2.Number2)

pandas.core.series.Series

In [ ]:
df2['Number2']  : Series type
df2[['Number2']] : DataFrame type
df2.Number2 : Series Type

In [86]:
import pandas as pd
df2 = pd.DataFrame()
number = [i for i in range(1, 11)]
square = [i ** 2 for i in range(1, 11)]
triple = [i ** 3 for i in range(1, 11)]
print(df2)
#cols = ['Number', 'Square','Triple']
df2['Number'] = number
df2['Square'] = square
df2['Triple'] = triple
df2

Empty DataFrame
Columns: []
Index: []


Number  Square  Triple
0       1       1       1
1       2       4       8
2       3       9      27
3       4      16      64
4       5      25     125
5       6      36     216
6       7      49     343
7       8      64     512
8       9      81     729
9      10     100    1000

In [ ]:
--- All values come in an array
 --- Array means it is a list of elements only represents using numpy package
 -- Generally elements present in 4 ways:

    - List : Basic representation

    - Numpay : Array with numpy package

    - Tensors : Tensorflow package

    - Torch : Pytorch package


In [87]:
list1 = [1, 2, 3, 4]
list1

[1, 2, 3, 4]

In [88]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [1]:
tensor([1,2,3,4])

NameError: name 'tensor' is not defined

In [99]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]
l1+l2


[1, 2, 3, 4, 10, 20, 30, 40]

In [100]:
import numpy as np
l1 = [1,2,3,4]
l2 = [10,20,30,40]
np1=np.array(l1)
np2=np.array(l2)
print(np1)
print(np2)
print(type(np1))
print(type(np2))
np1+np2

[1 2 3 4]
[10 20 30 40]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([11, 22, 33, 44])

In [101]:
df2['Number'].values
df2

Number  Square  Triple
0       1       1       1
1       2       4       8
2       3       9      27
3       4      16      64
4       5      25     125
5       6      36     216
6       7      49     343
7       8      64     512
8       9      81     729
9      10     100    1000

In [ ]:
**** How to save the dataframe?
**** Step-10 : Save the dataframe

 --- Datafarames are saveing in two frmats:
       --- 1> CSV: Comma Separated Values
       ---- 2> xlsx: Excel format

-- In order to save any data
    --- Where you want to save  : directory name
    --- What is the name of the file to storing
    ---- What is the extension

In [105]:
#Dataframe : df2
print(df2)
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

   Number  Square  Triple
0       1       1       1
1       2       4       8
2       3       9      27
3       4      16      64
4       5      25     125
5       6      36     216
6       7      49     343
7       8      64     512
8       9      81     729
9      10     100    1000


In [ ]:
*** Step-11:  How to read a dataframe?



In [110]:
import pandas as pd
dataframe_csv1 = pd.read_csv('Data1.csv')
print(dataframe_csv1)
dataframe_xls1 = pd.read_excel('Data1.xlsx')
print(dataframe_xls1)

   Unnamed: 0  Number  Square  Triple
0           0       1       1       1
1           1       2       4       8
2           2       3       9      27
3           3       4      16      64
4           4       5      25     125
5           5       6      36     216
6           6       7      49     343
7           7       8      64     512
8           8       9      81     729
9           9      10     100    1000
   Unnamed: 0  Number  Square  Triple
0           0       1       1       1
1           1       2       4       8
2           2       3       9      27
3           3       4      16      64
4           4       5      25     125
5           5       6      36     216
6           6       7      49     343
7           7       8      64     512
8           8       9      81     729
9           9      10     100    1000


In [107]:
import os
os.getcwd()

'C:\\Users\\nagal\\OneDrive\\Documents\\NareshIT\\EDA'

In [ ]:
**** step-13: How to avoid index column?

   -- While we save the dataframe
         -- Automatically a new column will create.
        



In [111]:
#### Save the data without index column, the file will not have index column
print(df2)
df2.to_csv('Data1.csv', index=False)
df2.to_excel('Data1.xlsx', index=False)

   Number  Square  Triple
0       1       1       1
1       2       4       8
2       3       9      27
3       4      16      64
4       5      25     125
5       6      36     216
6       7      49     343
7       8      64     512
8       9      81     729
9      10     100    1000
